# Generated by Django 4.0.2 on 2022-02-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_ad_category_mediacontent_adcategory_ad_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespOnAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responad', to='board.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responad', to='board.user')),
            ],
        ),
    ]
