# Generated by Django 4.0.2 on 2022-02-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_mediacontent_name_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='link_home_page',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
